name: "Provision the stack to build and deploy to GitHub Pages"

on:
  workflow_dispatch:
    inputs:
      NODE_VERSION:
        required: true
        description: 'Node.js version to be used'

jobs:
  setup:
    runs-on: ubuntu-latest
    environment:
       name: development
       url: ${{ steps.get-url.outputs.your_site }}

    steps:
      - name: 1 - Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: 2 - Setup Node to use the chosen version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ github.event.inputs.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: 3 - Generate framework code for a new Next.js application
        run: |
          npx create-next-app nextjs-scaffold --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
          cp -r nextjs-scaffold/* .
          rm -rf nextjs-scaffold
          echo ${{ github.event.inputs.NODE_VERSION }} > .nmvrc
          
      - name: 4 - Configure Git so that we can commit code to the repsitory
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
      - name: 5 - Commit the generated code and initialize the workflows
        run: |
          git add .
          git commit -m "Commit framework code and initialize workflows"
          git push origin -u main

      - name: 6 - Build the application
        run: |
          npm install
          npm run build 
          npm run env -- next export -o build
          
      - name: 7 - Deploy the application to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
     
      - name: 8 - Create the GitHub Pages site
        uses: actions/github-script@v4
        continue-on-error: true # API fails when the GitHub Pages is already deployed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'gh-pages',
                path: '/'
              }
            })
        
      - name: 9 - Print the URL of the website for the user's use
        run: |
          echo "Website URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          
      - name: Allow 10 minutes for the website to become available
        timeout-minutes: 10 
        id: get-url
        run: |
          echo "Waiting for the website to come alive..."
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          sleep 20
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          echo "STATUSCODE: $STATUS_CODE"
          while [ $STATUS_CODE -ne 200 ]
          do
            sleep 10
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
            echo "STATUSCODE: $STATUS_CODE"
          done
          echo "Website is up and running..."
          echo "Browse here: $URL"       
          echo "::set-output name=your_site::$URL"
